backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "proposal"
    label: "Proposals"
    folder: "content/proposal"
    create: true
    fields:
      - {label: "Company Name", name: "company_name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Logo", name: "logo", widget: "image"}