# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }

  - name: "proposals"
    label: "Proposals"
    folder: "content/proposals"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company Name", name: "company_name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Logo", name: "logo", widget: "image" }